local Translations = {
    houses = {
        ["title"]                  = 'Casa de Abelhas',
        ["capturing"]              = 'Caputrando Abelhas',
        ["queens"]                 = 'Rainhas (%{currentQueens} / %{maxQueens})',
        ["workers"]                = 'Trabalhadoras (%{currentWorkers} / %{maxWorkers})',
        ["destroy"]                = 'Destruir Casa de Abelhas',
        ["refresh"]                = 'Atualizar',
        ["withdraw_queens"]        = 'Retirar Rainhas',
        ["withdraw_workers"]       = 'Retirar Trabalhadoras',
        ["confirm_destroy"]        = 'Você tem certeza que deseja deletar essa Casa de Abelhas?',
    },
    hives = {
        ["title"]                  = 'Colmeia',
        ["producing"]              = 'Produzindo mel...',
        ["insert_queens"]          = 'Coloque %{needed} Rainha(s)',
        ["insert_workers"]         = 'Coloque %{needed} Trabalhadora(s)',
        ["honey_level"]            = 'Nível de Mel [%{currentHoney} / %{maxHoney}]',
        ["wax_level"]              = 'Nível de Cera [%{currentWax} / %{maxWax}]',
        ["destroy"]                = 'Destruir Colmeia',
        ["refresh"]                = 'Atualizar',
        ["withdraw_honey"]         = 'Retirar Mel',
        ["withdraw_wax"]           = 'Retirar Cerar',
        ["confirm_destroy"]        = 'Você tem certeza que deseja deletar essa Colmeia?',
    },
    target = {
        ["open_bee_house"]         = 'Casa de Abelhas',
        ["open_bee_hive"]          = 'Colmeia',
        ["beekeeper"]              = 'Falar com Apicultor',
    },
    beekeeper = {
        ["buy_bee_house"] = 'Comprar Casa de Abelhas',
        ["purchase_bee_house_desc"] = 'Compre uma Casa de Abelhas para coletar operárias e rainhas.',
        ["buy_bee_hive"] = 'Comprar Colmeia',
        ["purchase_bee_hive_desc"] = 'Obtenha uma Colmeia para começar a produzir mel e cera.',
        ["purchase_tools_title"] = 'Comprar Equipamentos de Apicultura',
        ["sell_honey"] = 'Vender Mel',
        ["sell_honey_desc"] = 'Venda seu mel colhido para obter lucro.',
        ["sell_wax"] = 'Vender Cera',
        ["sell_wax_desc"] = 'Comercialize sua cera de abelhas para diversos usos.',
        ["sell_products_title"] = 'Vender Produtos de Apicultura',
        ["purchase_tools"] = 'Comprar Ferramentas/Objetos',
        ["purchase_tools_desc"] = 'Compre ferramentas e objetos essenciais para apicultura.',
        ["sell_items"] = 'Vender Itens',
        ["sell_items_desc"] = 'Venda seus produtos de apicultura como Mel e Cera.',
        ["main_menu_title"] = 'Apicultor',
        ["return_main_menu"] = 'Retornar ao Menu Principal',
    },
    notifications = {
        ["title"] = 'Apicultura',
        ["incorrect_ground"] = 'Você não pode colocar isso aqui. O solo não é adequado.',
        ["already_placing"] = 'Você já está colocando um objeto.',
        ["not_enough_bees"] = 'Não há abelhas suficientes na casa.',
        ["not_enough_product"] = 'Não há produto suficiente na colmeia.',
        ["house_error"] = 'Erro com a Casa de Abelhas, por favor entre em contato com um administrador.',
        ["hive_error"] = 'Erro com a Colmeia, por favor entre em contato com um administrador.',
        ["owner_error"] = 'Esta colmeia/casa de abelhas não tem um proprietário, por favor entre em contato com um administrador.',
        ["inventory_full_bees"] = 'Você não tem espaço suficiente no seu inventário para coletar as abelhas!',
        ["inventory_full_products"] = 'Você não tem espaço suficiente no seu inventário para coletar os produtos!',
        ["not_enough_queens"] = 'Você não tem %{needed} rainha(s) com você.',
        ["not_enough_workers"] = 'Você não tem %{needed} operária(s) com você.',
        ["no_access"] = 'Você não é o proprietário.',
        ["max_limit_reached"] = 'Você atingiu o número máximo de colmeias/casas que pode colocar.',
        ["purchase_success"] = 'Compra de %{quantity} x %{product} realizada com sucesso.',
        ["not_enough_money"] = 'Dinheiro insuficiente para completar a compra.',
        ["sell_success"] = 'Venda de %{quantity} x %{product} realizada com sucesso.',
        ["not_enough_items"] = 'Itens insuficientes para vender.',
        ["in_exclusion_zone"] = 'Você não pode colocar uma colmeia/casa aqui!',
    },
    scaleforms = {
        ["cancel_button"] = 'Cancelar',
        ["place_button"] = 'Colocar Objeto',
        ["rotate_button"] = 'Rotacionar Objeto',
    },
}

Lang = Lang or Locale:new({
    phrases = Translations,
    warnOnMissing = true
})