local Translations = {
    error = {
        ["cannot_use_kit_here"]            = "Du kannst dieses Kit hier nicht verwenden.",
        ["already_hacked"]                 = "Dieses System wurde bereits gehackt.",
        ["still_active"]                   = "Das Sicherheitssystem ist immer noch aktiv.",
        ["fully_lockdown"]                 = "Das Sicherheitssystem ist vollständig abgeriegelt.",
        ["automatic_pressure_active"]      = "Die automatischen Druckregler sind aktiv.",
        ["automatic_pressure_active2"]     = "Die automatische Druckregulierung ist immer noch aktiv.",
        ["pressure_too_low"]               = "Der Druck ist zu niedrig und hat das Gerät blockiert.",
        ["incorrect_pass"]                 = "Falsches Passwort.",
        ["how_did_you_get"]                = "Hoppla, wie bist du hierher gekommen?!",
        ["not_enough_cops"]                = "Nicht genug Polizisten.",
        ["already_have_barrel"]            = "Du hast bereits ein Fass.",
        ["trying_to_exploit"]              = "Versuchst du hier etwa eine Schwachstelle auszunutzen?!",
        ["pressure_too_high"]              = "Der Druck ist zu hoch! Renn weg!!",
        ["cannot_hack_right_now"]          = "Du kannst das gerade nicht hacken.",
        ["pressure_not_right_yet"]         = "Der Druck stimmt noch nicht.",
        ["no_pink_usb_dongle"]             = "Du hast keinen pinken USB-Dongle.",
        ["cant_do_right_now"]              = "Das kannst du im Moment nicht tun.",
        ["wrong_lever_sequence"]           = "Sie haben die Hebel in der falschen Reihenfolge gezogen..",
    },
    success = {
        ["out_to_sea"]                     = "Du bist weit hinaus aufs Meer gefahren.",
        ["pressure_at"]                    = "Du benötigst einen Druck von ca. 55%.",
        ["pressure_at_2"]                  = "Sobald der Druck richtig ist, musst du bestimmte Bereiche hacken.",
        ["automatic_pressure_deactive"]    = "Automatische Druckregler deaktiviert.",
        ["took_barrel"]                    = "Du hast das Fass mit Öl genommen.",
        ["pulled_lever"]                     = "Hebel betätigt",
        ["current_pressure"]               = "Der aktuelle Druck beträgt:",
        ["security_system_override"]       = "Sicherheitssystem-Überschreibung gestartet.",
        ["find_levers_to_deactivate_pressure"] = "Du musst Hebel finden, um Druckregler zu deaktivieren.",
    },
    letters = {
        ["hidden_letter"] = "Der versteckte Buchstabe ist",
        ["first_hidden_letter"] = "Der erste versteckte Buchstabe ist",
        ["second_hidden_letter"] = "Der zweite versteckte Buchstabe ist",
        ["third_hidden_letter"] = "Der dritte versteckte Buchstabe ist",
        ["fourth_hidden_letter"] = "Der vierte versteckte Buchstabe ist",
    },
    menu = {
        ["input_password"]                 = "Geben Sie ein 4-Buchstaben-Passwort ein:",
        ["submit_Text"]                    = "Einreichen",
        ["uppercase_only"]                 = "Nur Großbuchstaben",
        ["sell_barrel"]                    = "Ölfass an diese Tankstelle verkaufen",
        ["going_price"]                    = "Aktueller Preis hier:",
    },
    prints = {
        ["cooldown_started"]  = "ÖLPLATTFORM: Abklingzeit gestartet",
        ["cooldown_finished"] = "ÖLPLATTFORM: Abklingzeit beendet",
    },
    target = {
        ["grab_barrel"]                    = "Fass nehmen",
        ["sell_barrel"]                    = "Ölfass verkaufen",
        ["pull_lever_1"]                   = "Hebel #1 betätigen",
        ["pull_lever_2"]                   = "Hebel #2 betätigen",
        ["pull_lever_3"]                   = "Hebel #3 betätigen",
        ["insert_dongle"]                  = "USB-Dongle einstecken",
        ["increase_pressure"]              = "Druck erhöhen",
        ["lower_pressure"]                 = "Druck verringern",
        ["check_pressure"]                 = "Druck überprüfen",
        ["enter_password"]                 = "Passwort eingeben",
        ["loot_body"]                      = "Durchsuchen",
    },
    progress = {
        ["reviving"]                       = "Wiederbeleben...",
        ["selling"]                        = "Verkaufen...",
        ["turning_valve"]                  = "Ventil drehen...",
        ["pickup_barrel"]                  = "Fass aufheben...",
    },
}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})